OD-5288 Support torch pt and pth models
OpendTect/dgbpy pull request #120
Opened 2024-01-29 12:41 UTC by marxprop

This PR will allow dgbpy support loading and saving models with the pt and the default torch model formats.

We'll only support the use of torch scripted models for now, 
`model = torch.jit.script(model)`

This would allow us not to depend on the architecture of the torch model itself while saving or loading the models. 
For more reference: https://pytorch.org/tutorials/beginner/saving_loading_models.html#export-load-model-in-torchscript-format

2024-01-29 13:11 UTC, arnauddgbes commented
See the comment left inside OD-5289, which will require come code change

2024-01-29 14:17 UTC, marxprop commented
Instantiating nn.Relu() in the forward method of model architectures raise issues during `torch.jit.script`

2024-01-30 12:29 UTC, arnauddgbes requested changes

2024-01-30 12:29 UTC, arnauddgbes commented on dgbpy/dgbtorch.py
> +    Torch = 'torch'
to be very clear I would name this one 'torchscript' (TorchScript' in the GUI)

2024-01-30 12:29 UTC, arnauddgbes commented on dgbpy/dgbtorch.py
> +  if dgbhdf5.isTorchModelFile( modelfnm ) and not dgbhdf5.isHDF5File( modelfnm ):
This does not belong here. modelfnm is exclusively the hdf5 file, thus never the model implementation for the PyTorch platform

The function _load_torch_pt_model may be exported, it does not need to stay internal.

2024-01-30 12:29 UTC, arnauddgbes commented on dgbpy/hdf5.py
> +def isHDF5File( filenm ):
not required, remove

2024-01-30 13:13 UTC, marxprop commented on dgbpy/dgbtorch.py
> +  if dgbhdf5.isTorchModelFile( modelfnm ) and not dgbhdf5.isHDF5File( modelfnm ):
Thanks @arnauddgbes , but I don't quite understand what you meant by the function can be exported.

During the first import of a pt/pth file, there is no hdf5 file.

2024-01-30 15:09 UTC, arnauddgbes approved these changes

2024-01-30 15:32 UTC, arnauddgbes requested changes

2024-01-30 15:32 UTC, arnauddgbes commented on dgbpy/torch_modelinfo.py
> +    return ''
Add:
```
if torch_model.__class__.__name__ == 'OrderedDict':
    return 'torch'
```

2024-01-30 15:32 UTC, arnauddgbes commented on dgbpy/torch_modelinfo.py
> +    return torch_model.original_name
check if the original_name attribute is valid for the object torch_model.
It won't be present for torch (pt) models
If not, return an empty string

2024-01-30 15:32 UTC, arnauddgbes commented on dgbpy/torch_modelinfo.py
> +    model = torch.jit.load( modelfnm )
here, disable warnings that may be printed if modelfnm is not a torchscript model

2024-01-30 15:33 UTC, marxprop commented on dgbpy/torch_modelinfo.py
> +    model = torch.jit.load( modelfnm )
this will raise an exception instead of printing a warning.

2024-01-30 15:53 UTC, arnauddgbes approved these changes

2024-01-30 16:19 UTC, arnauddgbes approved these changes

2024-01-30 16:19 UTC, merged