Saving and Loading models with S3
OpendTect/dgbpy pull request #141
Opened 2024-03-12 10:01 UTC by marxprop

2024-03-13 08:50 UTC, arnauddgbes approved these changes

2024-03-13 08:50 UTC, arnauddgbes commented on setup.py
> +        'boto3>=1.34.60',
move to extras_require, saving to s3 should be an optional extension

2024-03-13 09:28 UTC, arnauddgbes requested changes
minor change in setup.py

2024-03-18 12:00 UTC, arnauddgbes approved these changes

2024-03-18 12:01 UTC, arnauddgbes approved these changes

2024-03-18 12:01 UTC, arnauddgbes approved these changes

2024-03-29 11:25 UTC, marxprop commented
Closing this PR so as to open loading and saving as two separate PRs

2024-03-29 11:25 UTC, closed without merging