Create dgbcombine.py
OpendTect/dgbpy pull request #66
Opened 2023-04-13 07:31 UTC by hpratama

2023-04-13 07:59 UTC, arnauddgbes requested changes

2023-04-13 07:59 UTC, arnauddgbes commented on dgbpy/dgbcombine.py
> +def fit(models, inputs, outputs): # models, Xs, ys
Maybe nice to have, but does not fit as such in our workflow. You may copy it for reference to dgbscikit.py

2023-04-13 07:59 UTC, arnauddgbes commented on dgbpy/dgbcombine.py
> +def save_model(models, outfnm, save_type=defsavetype, input_shape=None):
Mostly duplicates dgbscikit.py:save
Let me propose the following signature:
dgbscikit.py:save( model, outfnm, save_type=defsavetype, prior_models=None )

Where prior_models is a set of already trained models.
If provided, you can add 'model' to the list 'prior_models', and save that extended list

2023-04-13 07:59 UTC, arnauddgbes commented on dgbpy/dgbcombine.py
> +def load_model(modelfnm, save_type=defsavetype):
I am not sure if this function does anything different from dgbpy.dgbscikit.load, so it can probably be removed.

2023-04-14 05:19 UTC, marxprop commented
@hpratama , I have compiled a detailed gist along with codes on the first steps which include setting up the train function in `dgbpy.dgbscikit ` to first of all handle training with multiple chunks and multiple folds. You can get ideas from this to help with your implementation. 

You can find it - [here](https://gist.github.com/marxprop/e321b7544a09d028cb4a7b21ebe4059d)

2023-06-14 07:27 UTC, arnauddgbes commented
Please rebase, and I can do a QC again

2023-06-14 07:27 UTC, arnauddgbes approved these changes

2023-10-18 06:11 UTC, closed without merging